services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "demodeploy"
      MARIADB_ROOT_PASSWORD: "demodeploypw"

volumes:
  db_data:
